### ISSUE TITLE
A Question On Ore

### ISSUE THREAD

**Issue by Belkachery1776** [AlanorMiga/Just-Enough-Guns#14]
Hello,

I came across your Mod and its really awesome. Got to look at all the features in creative and went ahead to play with the mod on survival... but there wasn't any 'scrap ore' in sight. Is the ore supposed to be that rare? Maybe it's just me having this incident. If it is a glitch, is there anything that may be affecting the spawn ability of the ore? 

Thanks for your time,

-Random player

**Comment by MigaMiDev** [comment]
It's supposed to be extremely common.

It could be a matter of using a ore-dense, modpack.

**Comment by Belkachery1776** [comment]
I'm sorry, I'm kind of new to mods. What is an example of a ore-dense mod pack?

________________________________

**Comment by MigaMiDev** [comment]
Perhaps you are using a modpack which adds a lot of ores. Or perhaps you had experimental world features disabled. Whichever the case is, I can guarantee that the latest JEG version spawns Ores if it was not manually disabled

**Comment by MigaMiDev** [comment]
![image](https://github.com/AlanorMiga/Just-Enough-Guns/assets/90504465/787578c6-4b54-4f94-9c4d-52e2220a513a)

Found a sample in a new world just 10 blocks away from spawn, for example.

**Comment by Belkachery1776** [comment]
You know what's funny? As soon as you reached out the ore is starting to appear like crazy.

Lol, I'm sorry for holding you up. this world is prob just barren beyond belief.

Thanks for replying though. Imma just close the problem online and look harder.

✌️🙏🙏
________________________________

**Comment by MigaMiDev** [comment]
Feel free to ask any further questions! Not holding me up!
