### ISSUE TITLE
[Suggestion] Unify the amount of space the items take in a slot

### ISSUE THREAD

**Issue by Camawama** [AlanorMiga/Just-Enough-Guns#17]
This might not be a huge thing on your to-do list but it would be nice to have them not overlap with other slots. Also, making it so the animations don't play with the item in the inventory since it looks weird especially if you drop the item on the ground mid-animation.

![image](https://github.com/AlanorMiga/Just-Enough-Guns/assets/43620900/e54582fa-837e-4128-a2a7-e5fc9245b2fc)

**Comment by MigaMiDev** [comment]
The space thing is not a to-do list currently.

The animation playing on the inventory I tried to fix and ask for help on the Geckolib official discord server but got ignored haha
