### ISSUE TITLE
[Bug] Guns get stuck in reload animation

### ISSUE THREAD

**Issue by Camawama** [AlanorMiga/Just-Enough-Guns#19]
https://github.com/AlanorMiga/Just-Enough-Guns/assets/43620900/33d91d40-52f5-4251-b349-dfb8de5f6939

**Comment by Camawama** [comment]
Can't ADS when this happens btw. It happened in the Unofficial port for MrCrayfish Gun Mod too..

**Comment by MigaMiDev** [comment]
If I recall correctly that is a Framework issue, not any of my mods issue, try downgrading Framework to 0.6.27
