### ISSUE TITLE
java.lang.NoClassDefFoundError 1.20.1

### ISSUE THREAD

**Issue by Showbiz53** [AlanorMiga/Just-Enough-Guns#20]
When I opened the mod with framework for 1.20.1 installed, it crashed giving me that error code up top saying tjhat it was solfware/bernie/geckolib/core/animatable/Geoanimatable.

**Comment by Showbiz53** [comment]
Found my issue. I had Geckolib in another folder. Sorry about that

**Comment by MigaMiDev** [comment]
It's totally fine!
