### ISSUE TITLE
Updating to the latest version is rejecting players from joining server

### ISSUE THREAD

**Issue by Zanklev** [AlanorMiga/Just-Enough-Guns#5]
I updated my server to the latest version you released today but it is causing players to be rejected due to something to do with packets. Here is the log. You can see it down at the bottom, right above where it mentions I failed to connect.

I even recreated a fresh server thinking it may not work with a pre-existing server but it's giving the same error again.

[latest.log](https://github.com/AlanorMiga/Just-Enough-Guns/files/15228301/latest.log)

**Comment by AlanorMiga** [comment]
I'm very sorry for this!
I have already uploaded a patch on CurseForge and Modrinth!

(If it hasn't been accepted on CurseForge, I'd suggest downloading it from Modrinth)

If any other issues pop up, please do let me know!
