### ISSUE TITLE
[Suggestion] JEI support

### ISSUE THREAD

**Issue by mpustovoi** [AlanorMiga/Just-Enough-Guns#7]
I mean it's not much but it's honest work. (It doesn't even display the number of items needed.)
![Original Gun Mod example](https://github.com/AlanorMiga/Just-Enough-Guns/assets/92390626/8570fb9e-61b0-43de-9d9e-6c1ca7c91c80)
(This screenshot was taken using EMI that has runtime JEI compat)
It can additionaly help to understand which workbench the player needs to create an item on.

**Comment by MigaMiDev** [comment]
Will be added in the near future, I will leave this thread open so I don't forget
